openshift/ironic-image

- Dockerfile.ocp
Change base image from centos7 to rhel7 for ocp container
> Build container from rhel7

- Dockerfile.ocp
Dockerfile.ocp was referring to a different file name
which is not being installed or is available to CI.
This filename was likey taken from downstream image
builds.
> Fix dockerfile.ocp for upstream openshift image builds

- dnsmasq.conf
Having DNS enabled causes issues when using this image on the bootstrap
node in openshift. If the dnsmasq container starts before coredns,
coredns refuses to start as dnsmasq has taken port 53.
> Disable listening for DNS

- Dockerfile
- Dockerfile.ocp
- configure-ironic.sh
- rundnsmasq.sh
- runhttpd.sh
- runironic-conductor.sh
Cherry-picks of the following upstream PRs
https://github.com/metal3-io/ironic-image/pull/88
https://github.com/metal3-io/ironic-image/pull/89
> Wait for provisioning interface and db sync

- Dockerfile
- Dockerfile.ocp
This pulls in the cleaning up /var/cache, and more importantly the fix that installs mkisofs so Ironic can build config drives. Otherwise with the latest BMO, you'll see a failure like this:
```
| last_error             | Failed to prepare the configdrive. Exception: Error generating the configdrive. Make sure the "genisoimage", "mkisofs" or "xorrisofs" tool is installed. Error: [Errno 2] No such file or directory: 'xorrisofs': 'xorrisofs'
```
> Sync dockerfile from upstream

- Dockerfile.ocp
- configure-ironic.sh
- inspector.ipxe
- ironic.conf
- runironic-exporter.sh
Adding packages installation and configuration to enable prometheus-exporter
Also removing explicit install of python-chardet, as dependency it will be installed anyway with the correct python version
> Enable prometheus-exporter

- Dockerfile.ocp
The package is needed for vmedia-boot to work correctly with idrac
Backport of https://github.com/metal3-io/ironic-image/pull/125
> Install python3-sushy-oem-idrac

- ironic.conf
The HPE virtual install device presents a virutal, emulated, read-only
spinning disk which fails cleaning operations in preparation for deployment.
This device is bios controlled, and is unable to be disabled by the user.
The bios may hide it in some cases if previously disabled before the bios
version is updated, or if "intellegent provisioning" has completed on the
host as the volume is intended for installation of other operating
systems.
Some more information can be found in storyboard:
https://storyboard.openstack.org/#!/story/2007229
This patch will likely be reverted once a fix for the device handling is
available in ironic-python-agent for downstream consumption.
rhbz: #1796141
> Bug 1796141: Temporarily disable cleaning as a workaround

- Dockerfile.ocp
We build an image during the build process and use it as builder.
This patch depends on https://github.com/openshift/release/pull/7010
> Bug 1798989: Use ubi8 based image as builder

- Dockerfile.ocp
- prepare-ipxe.sh
- rundnsmasq.sh
This is required for doing UEFI + IPv6 provisioning. It requires updated
iPXE packages.
--
Note: To be cherry-picked to 4.4 and 4.3.z, but will need to be done manually as it should include https://github.com/openshift/ironic-image/pull/43 as well.
4.4 BZ: 1807634 
4.3 BZ: 1807635
> Bug 1807633: Copy snpnoly.efi to tftpboot directory

- ironic.conf
It is currently pointing to a local file, but without
a file:// schema, so it is failing validation on
ironic.
Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
> Add schema to bootloader setting

- Dockerfile.ocp
This should fix the issues we're seeing sometimes where the
esp.img can't be copied to the final image.
> Add WORKDIR to builder

- Dockerfile.ocp
This should fix the issues we're seeing sometimes where the
esp.img can't be copied to the final image.
> Bug 1810145: Add WORKDIR to builder

- ironic.conf
It is currently pointing to a local file, but without
a file:// schema, so it is failing validation on
ironic.
Signed-off-by: Yolanda Robla yroblamo@redhat.com
> Bug 1809658: Add schema to bootloader setting

- Dockerfile.ocp
We recently tagged a new version of python3-openstacksdk to fix a bug,
but need a new image built to pull in the package.
> Whitespace change to trigger a new image build

- Dockerfile.ocp
- ironic.conf
Two patches from upstream image for virtmedia install
> virtmedia fixes

- dnsmasq.conf.j2
Currently the provisioning network DHCPv6 configuration ends up setting
a default route on hosts to be the metal3 pod itself.
This mailing list post[1] describes the problem in detail. We need to
set the ra-params for interval=0 and lifetime=0.
Cherry-pick of https://github.com/metal3-io/ironic-image/pull/145
[1] https://www.redhat.com/archives/libvir-list/2016-June/msg02203.html
> Bug 1814901: Disable default gateway for provisioning network in IPv6

- ironic.conf
When operating in an environment with networking issues, these two
seem to be the biggest sources of deployment/cleaning failures:
1) Substantially increase the number of retries for the ramdisk commands.
2) Enable PXE boot retries after 20 minutes of not hearing from the ramdisk.
See https://bugzilla.redhat.com/show_bug.cgi?id=1822763
> Bug 1822763: Increase command retries and add PXE booting retries

- dnsmasq.conf.j2
As part of the UEFI stack, a network stack is available. The iPXE
binary that implements this stack, and only this stack support is
snponly.efi, where as ipxe.efi instead tries to load network driers
that have been authored and incorporated into the ipxe.efi binary
itself.
These drivers are redundant in UEFI mode, and we should not need
them. As such, we should realistically only be using snponly.efi.
If not used, we get an error about no networks having been found
upon loading ipxe.efi.
rhbz# 1830161
> Bug 1830161: Use snponly.efi instead of ipxe.efi for IPv4

- ironic-common.sh
This fix introduces the fix created for metal3-io ironic-image https://github.com/metal3-io/ironic-image/pull/156/
Thanks @maelk for fixing our previous fix!
> bug 1833385: Allows users to configure any non-link-local IPV6 address for the provisioning interface

- ironic.conf
Sensor data collection was intended for an earlier use of
the ironic-image and resulting ironic container image in order
to supply data to prometheus about hardware that has not yet
been deployed upon. Since the deicsion was made not to leverage
the data, it seems pointless to collect sensor data.
As such, disable sensor data collection.
> Disable sensor data collection

- Dockerfile.ocp
This should fix the issues we're seeing sometimes where the
esp.img can't be copied to the final image.
(cherry picked from commit e263a5c90685f83217543519bbd17af248284613)
Plus change builder to ironic-builder to fix wrong base image.
> Bug 1847317: Add WORKDIR to builder

- configure-ironic.sh
- inspector.ipxe
- ironic.conf
- runhttpd.sh
Add ipa-api-url to inspector.ipxe and extra params in ironic.conf.
Without it ironic will never learn that the ramdisk has been booted
for inspection, requiring a reboot despite fast-track enabled.
NOTE: we need to configure everything in two places because there are
two inspection paths: discovery-style (via inspector.ipxe) and managed
(the same way as cleaning and deployment work).
Backport of https://github.com/metal3-io/ironic-image/pull/163 and https://github.com/metal3-io/ironic-image/pull/173
> Update inspection configuration to enable fast-track

- Dockerfile.ocp
- ironic.conf
Driver dependencies are now weak dependencies in RDO. Skip weak
dependencies and only install the ones we need explicitly.
> Skip weak dependencies and install driver libraries explicitly

- configure-ironic.sh
Ironic 15.x removes a long deprecated [conductor]api_url
parameter. This patch prepares for that by setting the correct
parameter, and notes in-line the old parameter that can be
eventually removed once OpenShift begins consuming ironic 15.x.
> Change endpoint URL recording for ironic 15.x

- ironic.conf
The default MD5 is not compatible with FIPS mode. See
https://bugzilla.redhat.com/show_bug.cgi?id=1853302
Upstream: https://github.com/metal3-io/ironic-image/pull/179
> Set the hash ring algorithm to SHA256

- configure-ironic.sh
- ironic.conf
- runironic-api.sh
- runironic-conductor.sh
- runironic.sh
* Expect all server credentials to be passed in the form of an `HTTP_BASIC_HTPASSWD` environment variable containing both the username and the *hash* of the password, in the htpasswd format.
* Expect client credentials to be passed in the form of a file named `/auth/ironic-inspector/auth-config` (for ironic-inspector) or `/auth/ironic-rpc/auth-config` (for the json-rpc interface to ironic-conductor), formatted as an ini config file setting the appropriate options (for basic auth, this is auth_strategy=http_basic, and the username and password options; however this mechanism should work unchanged for other auth strategies).
> Add HTTP Basic Auth support

- configure-ironic.sh
- runironic-api.sh
- runironic-conductor.sh
- runironic.sh
The ironic-conductor process needs to authenticate to the
ironic-inspector API, so we need to pass the auth config file options to
it also.
> Bug 1866032: Configure ironic-conductor to auth to ironic-inspector

- Dockerfile.ocp
- httpd-modules.conf
- httpd.conf
Leave httpd with the minimum needed for metal3,
in particular we wanted to disable directory listing and
http TRACE. But disabling everything we don't use seems
prudent.
> bug 1859334: Remove all unused modules

- configure-ironic.sh
Make the name consistent with inspector.ipxe.
Upstream: https://github.com/metal3-io/ironic-image/pull/190
> Bug 1866123: Use collector name in ironic.conf expected by IPA

- Dockerfile.ocp
This will allow to pass a custom list of packages to install during
build time with very little effort.
> Bug 1875300: Convert packages list to ARG

- configure-ironic.sh
- ironic.conf
Using crudini to merge this into ironic.conf no longer
works as it gets ignored as it matches the DEFAULT and
it is redundant. But later we then change the DEFAULT in
set_http_basic_server_auth_strategy so we need to set
json_rpc.auth_strategy back to noauth.
Downstream only patch to fix openshift-metal3/dev-scripts#1099 , this problem was fixed upstream during a switch to jinja2 for ironic.conf but a simpler patch is preferred in openshift so close to code freeze.
> Bug 1884155: Explicitly set json_rpc.auth_strategy to noauth

- ironic.conf
- main-packages-list.txt
ironic needs syslinux-nonlinux to generate a
bootable ISO image for virtmedia install on bios.
(cherry picked from commit a20cb04c80b784cf0b417229df1ec5b4880cb5ec)
> Bug 1862608: Install and configure for syslinux-nonlinux

- Dockerfile.ocp
Updating ironic builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ironic.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
> Updating ironic builder & base images to be consistent with ART

- ironic.conf
This was disabled to avoid an ironic bug that is now fixed, in
short ironic now Skips read-only devices when cleaning.
see
https://storyboard.openstack.org/#!/story/2007229
> Re-enable automated_clean

- ironic.conf.j2
- main-packages-list.txt
Reverts openshift/ironic-image#106
Unfortunately there is no syslinux-nonlinux package for ppc64le and this is causing mayhem during the build process for that architecture
> Revert "Bug 1862608: Install and configure for syslinux-nonlinux"

- Dockerfile.ocp
- ironic.conf.j2
The syslinux-nonlinux package is needed to generate a
bootable ISO image for virtmedia install on bios.
The package is available for x86_64 arch only, so we need a
conditional statement in the Dockerfile.
> Bug 1862608: Install syslinux-nonlinux

- ironic.conf.j2
Work around https://storyboard.openstack.org/#!/story/2008288 by setting
the DEFAULT.host config option to the host portion of a URL, meaning
that IPv6 addresses are surrounded by [], rather than just the raw IP
address. This is how it is ultimately used inside Ironic.
This solution works both with and without the fix for the issue in
Ironic (https://review.opendev.org/759877).
This patch is already merged upstream as metal3-io/ironic-image#211.
> Use [] around IPv6 address for conductor host config

- Dockerfile.ocp
- ironic.conf.j2
Avoid rebuilding GRUB2 since it invalidates its signature. Ironic
is able to build correct ISO images if you provide it with
a distribution specific EFI config path.
See https://review.opendev.org/760434
Upstream: https://github.com/metal3-io/ironic-image/pull/212
> Bug 1893648: Secure boot compatible ESP image

- configure-ironic.sh
12 is a lot of workers. With up to 100MiB of RAM per each, ironic-api
processes may occupy more than 1GiB of RAM in such configuration.
Since even CERN uses 2 workers in their configuration, we should
be fine with no more than 4. A similar change is made upstream:
https://review.opendev.org/761185
> Bug 1894146: Limit the default number of API workers to 4

- ironic.conf.j2
Add Redfish as a BIOS interface to allow retrieving BIOS configuration
using Redfish.
> Add additional drivers to enabled BIOS interface

- configure-ironic.sh
- ironic.conf.j2
We excluded these options from the initial proposal because they
reduce security. But since the provisioning IP may not be easily
predicted, it may be hard to generate suitable certificates, so
the insecure option is added to fascilitate two-step migration
from fully insecure HTTP to fully secure HTTPS.
Upstream: https://github.com/metal3-io/ironic-image/pull/229
> Add options to disable TLS validations

- ironic.conf.j2
This issue managed to sneak in during the last rebase.
Upstream: https://github.com/metal3-io/ironic-image/pull/232
> Bug 1906397: Fix incorrect IPA option

- Dockerfile.ocp
- prepare-image.sh
Convert the current PKGS_LIST to ENV as we should not really touch it.
Introduce the EXTRA_PKGS_LIST ARG to allow specifying a file
containing a list of extra packages to install.
The goal is to allow installing packages from different sources
to test them.
(cherry picked from commit a411a5aa6e9571e4095d52cc0d7e73ada6c2a9c7)
> Bug 1906806: Introduce separate ARG for extra packages list

- prepare-image.sh
Also make build process fail if something goes wrong in prepare-image
(cherry picked from commit 1c206964546bb18b0ddca8b47dd4bfe1a2a9ae1e)
> Bug 1909730: Prevent unbound variable error in prepare-image

- runironic-api.sh
Currently the API will start even if the conductor is still
starting up, which can lead to failures if you try to deploy
nodes as soon as the API is accessible.
Co-Author: Steven Hardy <shardy@redhat.com>
A change in the way ironic registers drivers is proposed here (this would also deal with the issue)
https://review.opendev.org/c/openstack/ironic/+/764911
> Bug 1902653: Wait for expected number of drivers starting API

- main-packages-list.txt
- prepare-image.sh
To simplify keeping track of minimum installed and required version
of python libraries and ironic packages, we add the versions in
the packages list.
This will also help when cross-tagging packages to test with the
new versions using the prevalidation repositories.
> Bug 1916145: Explicitly set minimum versions of python libraries

- main-packages-list.txt
We need a new version to fix the security vulnerability described in
https://access.redhat.com/security/vulnerabilities/RHSB-2021-001
> Bug 1917938: Update dnsmasq version

- Dockerfile.ocp
We need to upgrade the dnsmasq version to fix the vulnerability
described in https://access.redhat.com/security/vulnerabilities/RHSB-2021-001
> Bug 1917966: Force update of dnsmasq

- main-packages-list.txt
This PR contains a fix in the sushy package [1] for the bz [2]
[1] https://github.com/openstack/sushy/commit/dfe6b33fa66072e9ead784d06fa30946ef922cb8
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1915828
> Bug 1915828: Latest Dell firmware (04.40.00.00) fails to install IPI on BM using idrac-virtualmedia protocol

- main-packages-list.txt
The old version doesn't work very well with Fujitsu drivers.
> Bug 1920294: Update version of pyghmi library

- ironic.conf
This was disabled to avoid an ironic bug that is now fixed, in
short ironic now Skips read-only devices when cleaning.
see
https://storyboard.openstack.org/#!/story/2007229
> Bug 1903649: Re-enable automated_clean

- configure-ironic.sh
12 is a lot of workers. With up to 100MiB of RAM per each, ironic-api
processes may occupy more than 1GiB of RAM in such configuration.
Since even CERN uses 2 workers in their configuration, we should
be fine with no more than 4. A similar change is made upstream:
https://review.opendev.org/761185
> Bug 1899107: Limit the default number of API workers to 4

- main-packages-list.txt
Update fixes Redfish-virtualmedia (idrac) deploy fails on
"The Virtual Media image server is already connected"
https://bugzilla.redhat.com/show_bug.cgi?id=1910739
> Bug 1910739: Update ironic version to fix idrac bug

- main-packages-list.txt
Update adds vendor specific handling of BootSourceOverrideEnabled
as Supermicro requires it be set differently than other vendors.
https://bugzilla.redhat.com/show_bug.cgi?id=1918558
> Bug 1918558: Update ironic version with Supermicro boot fix

- Dockerfile.ocp
- main-packages-list.txt
To simplify keeping track of minimum installed and required version
of python libraries and ironic packages, we add the versions in
the packages list.
This will also help when cross-tagging packages to test with the
new versions using the prevalidation repositories.
Partial cherry-pick from #132
> Bug 1918178: Explicitly set minimum versions of ironic packages

- Dockerfile.ocp
Supplying a blank arg to COPY results in all of
the files in the source directory being copied into
the image into /tmp for docker/podman build (or "/"
if using imagebuilder). Give it a default of a file
that exists to avoid this happening.
cherry-picked from upstream
https://github.com/metal3-io/ironic-image/pull/239
> Supply a default for COPY args

- Dockerfile.ocp
`podman`, `buildah`, and basically any other image building method merges the new contents of `scripts/` with `/bin/`, but `imagebuilder` overrides them instead.
Test:
Given the following sample Dockerfile:
```
FROM registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-base:ubi8
RUN ls /bin/ | wc -l
COPY scripts/ /bin/
RUN ls /bin/ | wc -l
```
Building it with `buildah`, does what is expected:
```
$ buildah bud
STEP 1: FROM
registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-base:ubi8
STEP 2: RUN ls /bin/ | wc -l
364
STEP 3: COPY scripts/ /bin/
STEP 4: RUN ls /bin/ | wc -l
374
STEP 5: COMMIT
```
But with `imagebuilder`:
```
$ imagebuilder .
--> FROM
registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-base:ubi8 as
0
--> RUN ls /bin/ | wc -l
364
--> COPY scripts/ /bin/ …
```
> Prevent content override of /bin/ when building with imagebuilder

- runironic-api.sh
Currently the API will start even if the conductor is still
starting up, which can lead to failures if you try to deploy
nodes as soon as the API is accessible.
Co-Author: Steven Hardy <shardy@redhat.com>
> Bug 1917481: Wait for expected number of drivers starting API

- main-packages-list.txt
Start tagging new versions of ironic and sushy packages for OCP 4.8
> Start using current ironic versions

- Dockerfile.ocp
Supplying a blank arg to COPY results in all of
the files in the source directory being copied into
the image into /tmp for docker/podman build (or "/"
if using imagebuilder). Give it a default of a file
that exists to avoid this happening.
> Bug 1937695: Supply a default for COPY args

- main-packages-list.txt
Sync ironic, ironic-lib and sushy with latest needed changes.
> Update packages to pick up latest changes

- Dockerfile.ocp
This is to avoid failures when building the image due to "Disk full"
> Bug 1953670: Increase ESP size

- config/ironic.conf.j2
Set the ironic conf setting `webserver_verify_ca` to a
new WEBSERVER_CACERT_FILE env if defined, or set it
the value of IRONIC_INSECURE if the cert is not defined.
By default it will be set to True.
> Bug 1953795: Set webserver_verify_ca to certificate path or false

- config/ironic.conf.j2
- main-packages-list.txt
The new ramdisk_image_download_source allows to set where the boot iso
image will be served from.
The new ramdisk_image_download_source allows to set where the boot iso
image will be served from.
Also set ironic version to the change where the option was added [0].
[0] https://opendev.org/openstack/ironic/commit/659eef72ee59fdeb639577c8499406f59644a433
Metal3 change https://github.com/metal3-io/ironic-image/pull/261
> Bug 1953979: Add parameter to set boot iso source

- main-packages-list.txt
python-eventlet: improper handling of highly compressed data and memory
allocation with excessive size allows DoS.
> Bug 1958802: Include fix for CVE-2021-21419

- main-packages-list.txt
Where the commits have not changed, the RPM spec files were resynced to the RDO/Wallaby versions at the time they were built.
https://bugzilla.redhat.com/show_bug.cgi?id=1961717
Signed-off-by: Lon Hohberger <lhh@redhat.com>
> Bug 1961717: Update dependencies to Wallaby versions

- scripts/configure-ironic.sh
Ironic's approach to caching ISOs and serving them to Apache is well supported by most BMCs and defaulting to it would increase the compatibility of the solution. Switching the default to "local" should come with documentation of the storage requirements, specially in the usage pattern introduced by the Agent based fully automated provisioning.
This reverts commit 39bd4c55e3e6847a0120f26634a65cf26a2b00e5.
> Bug 1962905: Revert "Disable caching live boot iso by default"

- config/ironic.conf.j2
When bios_interface is set to irmc, the master will continue to restart during the IPI
configuration process, so temporarily remove irmc from enabled_bios_interfaces.
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>
> Bug 1969212: remove irmc from enabled_bios_interfaces

- config/ironic.conf.j2
This commit adds the new ironic configuration option
``[ipmi]/cipher_suite_versions``.
Allowing ipmi to try different values in case of the
default cipher suite is not supported.
https://bugzilla.redhat.com/show_bug.cgi?id=1897415
> Bug 1897415: Add cipher_suite_versions config

- scripts/runironic-api
Ironic has been fixed, the work around is no longer needed.
Reverts openshift/ironic-image#134
> Revert Wait for expected number of drivers starting API

- README.md
- scripts/ironic-common.sh
The point of this PR is to allow users to:
not have to provide the PROVISIONING_INTERFACE (as it has to be the same for all hosts)
instead make use of the know mac addresses that we have in the bmh.Spec.BootMACAddress to calculate the interface
The cbo PR is here openshift/cluster-baremetal-operator#149
> Add support for deriving the PROVISIONING_INTERFACE from a mac address

- ironic-config/ironic.conf.j2
- scripts/configure-ironic.sh
In order to allow provisioning of external nodes, we need to be able to
call back to Ironic on an external IP address.
This is from an upstream patch:
https://github.com/metal3-io/ironic-image/commit/88dde3112a372607855740db6ec203e3d6800129
> Add options for external_http_url and external_callback_url

- Dockerfile.ocp
- Dockerfile.okd
- ironic-config/ironic-python-agent.ign.j2
- ironic-config/ironic.conf.j2
- main-packages-list.txt
- scripts/configure-coreos-ipa
- scripts/configure-ironic.sh
- scripts/coreos-ipa-common.sh
- scripts/runhttpd
* Clean up [inspector]extra_kernel_params
* Enable the custom-agent deploy interface
* Allow configuring CoreOS IPA as a new entrypoint
> Support IPA running on top of CoreOS

- scripts/configure-coreos-ipa
It is possible to only use PXE artefacts, in which case we need to
generate an ignition file, but don't need to customize the ISO.
Increase verbosity of configure-coreos-ipa for debugging.
> Custom deploy: do not require an ISO

- ironic-config/ironic-python-agent.ign.j2
We're not ready yet to enable host validation for agent->ironic
connection, use insecure=True as we do for PXE.
> Custom deploy: disable TLS host validation in the agent

- ironic-config/ironic.conf.j2
- scripts/configure-ironic.sh
In order for IPA to call back into ironic inspector when being
used on external networks, we'll need to set this as well.
> Add inspector callback_endpoint_override

- prepare-image.sh
This change adds a flag that disables installing documentation from
RPMs. Additionally, prevent installing weak dependencies globally.
(cherry picked from commit 178b7675ea57c02b67f2614a2267eedf219e0b8e)
metal3-io PR https://github.com/metal3-io/ironic-image/pull/281
> Bug 1989839: Prevent installing docs via a DNF flag

- main-packages-list.txt
Include some recent bugfixes from ironic upstream code, for example:
https://opendev.org/openstack/ironic/commit/48cedc067a2436f60de10bb9cdfb1e29f57928ee
https://opendev.org/openstack/ironic/commit/ff05ba063e8842e4de97f908eed5a9e90239f1a5
https://opendev.org/openstack/ironic/commit/4037ae147af3b3b9a1a2e732a6e4ea732e2f51fc
> Bug 1975137: [4.8] Sync image with the latest ironic code

- main-packages-list.txt
This commit updates ironic-images so that this sushy fix:
https://review.opendev.org/c/openstack/sushy/+/803197
is included.
> Bug 1986238: Supermicro X12 fails to provision using Redfish BM HW Provisioning

- ironic-config/ironic.conf.j2
- scripts/runironic-api
Auth was removed from ironic API in favour of doing
it in httpd (as part of a switch to wsgi). The switch to
wsgi hasn't happened so we need to restore auth here.
> Bug 1993078: Restore auth config to ironic-api

- main-packages-list.txt
Include recent bug fixes from upstream code:
https://github.com/openstack/ironic/commit/8f6a2eacebdc767d98a3c0737329bf8825c1adcb
https://github.com/openstack/ironic/commit/5b801be7a456e31c5111971a3ecc2ad140b19ea5
> Bug 1991979: [4.8] Sync image with ironic

- OWNERS
He's the current Ironic PTL (project team lead) and is well familiar
with the code, as well as the way images are built and shipped.
Stephen is moving on to different responsibilities and is not very active
on ironic-image anyway.
> OWNERS: add iurygregory, remove stbenjam

- main-packages-list.txt
This commit bumps sushy to the the latest build
python-sushy-3.7.3-0.20210804111215.b76050c.el8
that includes a fix to support virtualmedia on SMC
> Bug 2003035: Sync sushy to include the latest bugfixes for 4.8

- scripts/configure-coreos-ipa
This is no longer needed since openshift/cluster-baremetal-operator#202,
which passes the proper OpenShift image to the configure-coreos-ipa
script.
> Remove unsafe default for IRONIC_AGENT_IMAGE

- main-packages-list.ocp
- main-packages-list.okd
- scripts/ironic-common.sh
The ip command returns the short-form of the IPv6 address so that is what should be used for comparison, even if the user entered an IPv6 address in long-form for PROVISIONING_IP. Use ipcalc to get the short-form address. This command can also be used for IPv4 as it strips out the subnet mask for IPv4 and IPv6.
For the PROVISIONING_IPs below, this is what would be set for IRONIC_IP:
fdcc:aaaa:00bb:c1d0::3 -> fdcc:aaaa:bb:c1d0::3
fdcc:aaaa:00bb:c1d0:0000:0000:0000:0003 -> fdcc:aaaa:bb:c1d0::3
fdcc:aaaa:00bb:c1d0::3/64 -> fdcc:aaaa:bb:c1d0::3
fdcc:aaaa:00bb:c1d0::3/128 -> fdcc:aaaa:bb:c1d0::3
10.10.10.1 -> 10.10.10.1
10.10.10.1/24 -> 10.10.10.1
10.10.10.1/64 ->
> Bug 2010698: Compare IPs using the short form of IPv6 address

- main-packages-list.ocp
See https://bugzilla.redhat.com/show_bug.cgi?id=2014630 for more info
> Bug 2014630: Update ironic to fix image provisioning fails with file name too long

- main-packages-list.txt
This commit brings in the upstream OpenStack/Sushy fix required
for virtual media based provisioning of SuperMicro X11 and X12
into OpenShift:
https://review.opendev.org/c/openstack/sushy/+/818369
> Bug 2025754: Enable vMedia provisioning of SuperMicro X11/X12

- main-packages-list.txt
This commit brings in the upstream OpenStack/Sushy fix required
for virtual media based provisioning of SuperMicro X11 and X12
into OpenShift:
https://review.opendev.org/c/openstack/sushy/+/818364
> Bug 2025755: Enable vMedia provisioning of SuperMicro X11/X12

- main-packages-list.ocp
This commit pulls in the latest ironic-master into OpenShift, 
bringing a number of bugfixes and enhancements.
> Bring Ironic version to 18.3.0-0.20211206200515.0ff3da2

- scripts/coreos-ipa-common.sh
When we get images from the image builder, they will contain the
Ignition file. Only pass an Ignition URL on the kernel command line if
the configure-coreos-ipa script has been run to create an ignition file
locally. We will not run this script when using the image builder.
However, we always want to set the rootfs location in the kernel args,
even when we haven't run configure-coreos-ipa because we are using the
image builder instead.
(Upstream PR is metal3-io#331)
> Don't always pass ignition config in PXE kernel args

- ironic-config/ironic.conf.j2
This new feature provides a history of all events for a node. We don't
use it, and it creates an additional load on the database. Disable.
Upstream: https://github.com/metal3-io/ironic-image/pull/336
> Disable the node history feature

- main-packages-list.ocp
Do not validate boot interface when local booting [1]
Fix redfish update_firmware for newer Sushy [2]
[1] https://opendev.org/openstack/ironic/commit/d5c47ac862d8afbd23e0cac2aef58dd83e665af9
[2] https://opendev.org/openstack/ironic/commit/e09f09f689e25b46ee41a32210717c0a51c2d499
> Bug 2032573: Update ironic to include latest major bugfixes

- Dockerfile.ocp
- main-packages-list.ocp
- patches/001-Allow-reusing-defaults-in-per-node-kernel_append_params.patch
Backports Ironic commit 5feb39844ab1a3f266669f01b6a13f39462b4612 to 4.11.
Required by:
- https://github.com/openshift/enhancements/pull/1059
- https://github.com/metal3-io/baremetal-operator/pull/1109
> [OCP 4.11 only] Backport the kernel params patch

- main-packages-list.txt
This commit brings the upstream OpenStack/Sushy fixes required
for virtual media based provisioning of Nokia servers into
OpenShift:
https://review.opendev.org/c/openstack/sushy/+/839843
https://review.opendev.org/c/openstack/sushy/+/839844
https://review.opendev.org/c/openstack/sushy/+/839845
> Bug 2082103: Enable vMedia provisioning of Nokia servers

- main-packages-list.txt
This commit brings the upstream OpenStack/Sushy fixes required
for virtual media based provisioning of Nokia servers into
OpenShift:
https://review.opendev.org/c/openstack/sushy/+/840653
https://review.opendev.org/c/openstack/sushy/+/840654
https://review.opendev.org/c/openstack/sushy/+/840655
> Bug 2048672: Enable vMedia provisioning of Nokia servers

- main-packages-list.ocp
This commit bumps the ironic version to the latest brew build [1]
that includes the fix for BZ2087213 [2]
[1] https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2069315
[2] https://opendev.org/openstack/ironic/commit/b5ed57a60001894ebc5ed56ec39eca0c3ee518fc
> Bug 2087213: Ironic Fix for ZTP with 4.11

- Dockerfile.ocp
- Dockerfile.okd
- ironic-config/apache2-proxy.conf.j2
- scripts/runironic-proxy
In OpenShift we deploy Ironic only on one of the controlplane nodes.
When the provisioning network is disabled, IPA talks to Ironic API via
the node's IP address. If the Metal3 pod is relocated, IPA loses contact
to Ironic API.
Upstream in Metal3, this problem is solved via keepalived. We don't want
to introduce another VIP in OpenShift, so instead this change adds
a new script that launches httpd as a proxy to real Ironic. It will be
deployed as a DaemonSet, making Ironic API available on the API VIP.
The cluster-baremetal-operator will be responsible for updating
the DaemonSet with the up-to-date real Ironic IP address.
> METAL-256: Add a new entry point for the Ironic proxy

- ironic-config/apache2-proxy.conf.j2
The way httpd works, it requires a strict match of CommonName even if IP
addresses are provided in SubjectAltName. This is not a setup we can
support. On the other hand, we can validate the Ironic peer uses
the same TLS certificate as we, so let's do it.
> ironic-proxy: never validate TLS peer name

- ironic-config/apache2-ironic-api.conf.j2
- ironic-config/apache2-proxy.conf.j2
- ironic-config/apache2-vmedia.conf.j2
- ironic-inspector-config/inspector-apache.conf.j2
ServerName does not support IPv6 addresses, the verification fails when the second segment doesn't begin in a digit(it doesn't look enough like a port number).
We only have a single VirtualHost per "Listen" so it is the default. Remove the use of ServerName as we're not using it to differentiate between VirtualHosts.
> Removed ServerName from VirtualHost Directives

- main-packages-list.ocp
This commit backports upstream changes in OpenStack/Ironic which resolve https://issues.redhat.com/browse/OCPBUGS-2011 in OpenShift 4.11:
https://review.opendev.org/c/openstack/ironic/+/859916
https://review.opendev.org/c/openstack/ironic/+/860307
> OCPBUGS-2011: Backport improvements to iDRAC steps to OCP 4.11

- main-packages-list.ocp
This commit backports upstream changes in OpenStack/Ironic which resolve https://issues.redhat.com/browse/OCPBUGS-1740 in OpenShift 4.10:
https://review.opendev.org/c/openstack/ironic/+/859918
https://review.opendev.org/c/openstack/ironic/+/860308
> OCPBUGS-1740: Backport improvements to iDRAC steps to OCP 4.10

- ironic-config/apache2-ironic-api.conf.j2
- ironic-config/apache2-vmedia.conf.j2
- ironic-inspector-config/inspector-apache.conf.j2
ServerName does not support IPv6 addresses, the verification fails when the second segment doesn't begin in a digit(it doesn't look enough like a port number).
We only have a single VirtualHost per "Listen" so it is the default. Remove the use of ServerName as we're not using it to differentiate between VirtualHosts.
> OCPBUGS-1972: Removed ServerName from VirtualHost Directives

- scripts/configure-ironic.sh
This change stops saving the OS_ prefixed variables to a file but keeps them logged on stdout. The file is not consumed elsewhere, by either this image or Ironic itself. Outputting to a container instance's stdout allows some other log collector to save what may be helpful debugging information about the Oslo configuration, and adding the: `|| true` allows for base images without OS_ unset to cause a non-zero return code with pipefail set.
This is a reworded cherry-pick of [the upstream PR](https://github.com/metal3-io/ironic-image/pull/392).
> OCPBUGS-2992: Don't save OS_ prefixed variables

- ironic-config/dnsmasq.conf.j2
- scripts/rundnsmasq
May be very useful when early resolving of hostnames is required.
> Allow dnsmasq to work as a DNS forwarder

- README.md
- ironic-config/dnsmasq.conf.j2
- scripts/configure-httpd-ipa.sh
- scripts/configure-ironic.sh
- scripts/rundnsmasq
- scripts/runhttpd
SECURITY_CONTACTS has been removed to avoid confusion.
Source-based installation is still removed as well.
> OCPBUGS-1844: Merge from upstream metal3-io/ironic-image

- prepare-image.sh
It forces using /var/log/ironic/ironic.log, which is not necessary in containers and also grows indefinitely since log rotation is not enabled.
(cherry picked from commit 8621a3bcba872767901efca7fe8bd6b888bdea59)
> Bug OCPBUGS-4305: Remove RDO distribution configuration (finally fixes #46)

- main-packages-list.txt
This commit brings the upstream OpenStack/Sushy fixes improving eTag handling into OpenShift 4.9
https://review.opendev.org/c/openstack/sushy/+/862849
> [4.9] Bug OCPBUGS-1246: Improve resiliency of eTag handling

- ironic-config/ironic.conf.j2
Configuring iLO Ironic driver to use web server for hosting images. This resolves an issue where it defaults to swift while running in standalone mode, breaking virtual media provisioning.
(cherry picked from commit a192a75282a1a025f1455ffcdd96ceebf79abd82)
> OCPBUGS-5068: Configure Ironic iLO driver to use web server

- main-packages-list.ocp
Dosfstools and util-linux provide mkfs and mkfs.vfat binaries which are required for image creation operations performed by iLO driver.
(cherry picked from commit 2327eed04d27fd452c5f3e117f30b31d872f885f)
> OCPBUGS-5136: Adding dosfstools and util-linux tools to ironic-image

- main-packages-list.ocp
Dosfstools and util-linux provide mkfs and mkfs.vfat binaries which are required for image creation operations performed by iLO driver.
(cherry picked from commit 2327eed04d27fd452c5f3e117f30b31d872f885f) (cherry picked from commit 0406cf5126fe6a48add67ef34f570700ae0655b4)
> [4.11] Bug OCPBUGS-5404: Adding dosfstools and util-linux tools to ironic-image

- ironic-config/ironic.conf.j2
There have been cases on some hardware where the power state change takes longer than the current default (60 seconds) to be reported. This does not need to be configurable.
> OCPBUGS-7163: Increase power_state_change_timeout setting

- main-packages-list.ocp
OCPBUGS-7567: CVE-2023-25577 python-werkzeug: high resource usage ...
OCPBUGS-7564: CVE-2023-23934 python-werkzeug: cookie prefixed with =..
> Adding dep on python3-werkzeug >= 2.0.3-4

- main-packages-list.ocp
OCPBUGS-7567: CVE-2023-25577 python-werkzeug: high resource usage ...
OCPBUGS-7564: CVE-2023-23934 python-werkzeug: cookie prefixed with =..
> OCPBUGS-7566: Bump werkzeug 4.12

- Dockerfile.fcos
- Dockerfile.ocp
- Dockerfile.scos
- README.md
- configure-nonroot.sh
- prepare-image.sh
- scripts/ironic-common.sh
- scripts/rundnsmasq
- scripts/runhttpd
- Fix source build if building sushy from source
- Fix PROVISIONING_MACS unbound in centos httpd
- Dockerfiles: use apt-get instead of apt
- Add Lennart and Adam as reviewers
- Remove RDO distribution configuration (finally fixes #46)
- Configure Ironic iLO driver to use web server
- Adding dosfstools and util-linux tools to ironic-image
- Use sushytools port from the config file
- Add ironic IP to no_proxy
- docs(readme): fix environment variable formatting
- update user-guide url
- set docker registry url to docker.io
- make ironic-image runnable as non-root
> Merge from upstream metal3-io/ironic-image

- main-packages-list.ocp
Also fix oslo-messaging dependency
> OCPBUGS-8068: Fix for node's last_error disappears briefly on cleaning failure

- main-packages-list.ocp
OCPBUGS-7567: CVE-2023-25577 python-werkzeug: high resource usage ...
OCPBUGS-7564: CVE-2023-23934 python-werkzeug: cookie prefixed with =..
> OCPBUGS-7565: Adding dep on python3-werkzeug >= 2.0.3-4

- ironic-config/ironic.conf.j2
Intended as a temporary change, this bumps the min_command_interval to 30 on SCOS.
The infrastructure that the OKD Streams build system is going to be deployed to uses an IPMI proxy which introduces additional latency on that specific infrastructure.
Increase min_command_interval until a faster proxy is used. Only affects OKD/SCOS builds of ironic-image.
/cc @derekhiggins
> OCPBUGS-14132: ironic.conf.j2: Bump min_command_interval to 30 on SCOS

- main-packages-list.ocp
Patched version includes fix for
https://bugzilla.redhat.com/show_bug.cgi?id=2196643
> OCPBUGS-13699: Add python-flask dependency

- main-packages-list.ocp
This includes an important fix for database lock that could cause ironic to hang and not complete any operation, causing the deployment to fail
> OCPBUGS-17142: [4.14] Update packages with latest bugfix

- Dockerfile.fcos
- Dockerfile.scos
Exclude also = character in case we need to pin versions for OCP
> OCPBUGS-17472: Expand regex for fcos/okd packages list

- Dockerfile.fcos
- Dockerfile.scos
current-triple is no longer maintained and doesn't contain recent fixes we require.
> OCPBUGS-19019: Switch from current-tripleo to puppet-passed-ci

- main-packages-list.ocp
Ironic sync PR https://github.com/openshift/openstack-ironic/pull/47
> OCPBUGS-9303: update Ironic to include secure boot fixes

- scripts/ironic-common.sh
Provides more debugging info and can avoid situation where the pipe hides errors.
> OCPBUGS-21876: Use bash process substitution instead of pipe

- scripts/ironic-common.sh
Provides more debugging info and can avoid situation where the pipe hides errors.
> OCPBUGS-23072: Use bash process substitution instead of pipe

- main-packages-list.ocp
[4.13] Ironic side of external_http_url ([METAL-163](https://issues.redhat.com//browse/METAL-163)) is not wired in correctly
> OCPBUGS-23978: Ironic side of external_http_url (METAL-163) is not wired in correctly

- main-packages-list.ocp
Ironic side of external_http_url ([METAL-163](https://issues.redhat.com//browse/METAL-163)) is not wired in correctly
> OCPBUGS-23979: Ironic side of external_http_url (METAL-163) is not wired in correctly

- main-packages-list.ocp
Also relax the package requirements in the same spirit as on master.
> OCPBUGS-19884: update Ironic to include secure boot fixes

- ironic-config/inspector.ipxe.j2
use IRONIC_URL_HOST instead of IRONIC_IP in inspector iPXE config to account for IPv6 addresses
Signed-off-by: Himanshu Roy <hroy@redhat.com>
(cherry picked from commit fd52a46b6c5f579009c79023e901a7291830ca4e)
> OCPBUGS-22699: Fix Inspector iPXE config for IPv6 addresses

- ironic-config/inspector.ipxe.j2
use IRONIC_URL_HOST instead of IRONIC_IP in inspector iPXE config to account for IPv6 addresses
Signed-off-by: Himanshu Roy <hroy@redhat.com>
(cherry picked from commit fd52a46b6c5f579009c79023e901a7291830ca4e) (cherry picked from commit ab442054f273aad7c33b137b1a79b10b86f88056)
> [release-4.14] OCPBUGS-27193: Fix Inspector iPXE config for IPv6 addresses

- Dockerfile.ocp
- main-packages-list.ocp
- prepare-image.sh
- requirements.cachito
Stop using RPMs for ironic and ironic-inspector and install all their services from source code directly, using the openshift forks.
> METAL-849: Install ironic and ironic-inspector from source

- .gitignore
- Makefile
- tools/check-requirements.sh
Also add Makefile with build and check requirements actions, plus gitignore.
The check-reqs.sh script can be used to determine if the commit hashes in the requirements.cachito file belong to the correct release branch.
The check will be automated with a CI job after more tests.
> METAL-922: Add check requirements script

- main-packages-list.ocp
Recently lextudio dropped pyasn1 so we want to be explicit and show that we install pysnmp-lextudio but normal pyasn1.
> METAL-949: Force pysnmp-lextudio and pyasn1 min version

- prepare-image.sh
Assign specific user ID to the ironic user, and group IDs to the ironic and inspector groups. Now openshift/CBO also expects the inspector container to be run this way due to [PR#417](https://github.com/openshift/cluster-baremetal-operator/pull/417/files). 
This is done to fix permissions issues with the ironic-inspector container where it fails to create the /certs/ca/ironic directory.
> OCPBUGS-32304: Fix ironic-inspector permissions for creating /certs/ca directory

- prepare-image.sh
Installing compiled python files through pip can cause issues in FIPS-enabled environments. This change disables installing those files through pip and compiles them locally instead.
> Bug OCPBUGS-34534: Disable installation of .pyc files through pip

- prepare-image.sh
Installing compiled python files through pip can cause issues in FIPS-enabled environments. This change disables installing those files through pip and compiles them locally instead.
(cherry picked from commit cae9cda780ec7f0857e51763f2e2e626ab86243d)
> [4.15] Bug OCPBUGS-33736: Disable installation of .pyc files through pip

- prepare-image.sh
Installing compiled python files through pip can cause issues in FIPS-enabled environments. This change disables installing those files through pip and compiles them locally instead.
(cherry picked from commit cae9cda780ec7f0857e51763f2e2e626ab86243d)
> [4.14] Bug OCPBUGS-34657: Disable installation of .pyc files through pip

- requirements.cachito
See https://review.opendev.org/c/openstack/ironic-inspector/+/921875
> OCPBUGS-32261: Update ironic-inspector to fix the memory leak

- prepare-image.sh
- requirements.cachito
Since in CI we use the --no-index option to emulate a pip disconnected environment to try and reproduce the downstream build conditions, it's not possible to test normal dependencies from source as pip won't be able to retrieve them from any remote source.
To work around that we download all the packages first removing the --no-index option but using the --no-deps option, preventing downloading dependencies.
This forces to download only the packages specified in the requirements file, ensuring total control on main libraries and dependencies and allowing us to be as granular as needed, easily switching between RPMs and source packages for testing or even for downstream builds.
When we install them afterwards if any dependency is missing the installation process will fail in CI, allowing …
> METAL-1049: Download and install sources from local dir

- main-packages-list.ocp
> OCPBUGS-33335: Update Python Jinja2

- main-packages-list.ocp
The current version we have installed is `python-jinja2-3.0.1-2.el9.1`, in `main-packages-list.ocp` the prefix `2-` in the version is a typo that got introduced in the past.
Fixing the typo and bumping to the new version `3.0.1-3.el9.1` to fix the bug.
> [4.12] OCPBUGS-34897: bump jinja2

- .ci-operator.yaml
Most recent available is still from 4.17 but we should update it to avoid errors in the pipeline as the current one is too old.
> OCPBUGS-38406: Update root image

- prepare-image.sh
Suppress the listing of files and directories being compiled/searched. compileall will still output any errors but they will no longer get lost in the 3000+ lines of output.
> METAL-1123: Suppress file listing of compiled py files

- .ci-operator.yaml
we should update it to avoid errors in the pipeline as the current one is too old.
> OCPBUGS-38481: Update root image

- requirements.cachito
See https://review.opendev.org/c/openstack/ironic-inspector/+/921875
> OCPBUGS-42113: Update ironic-inspector to fix the memory leak

- prepare-image.sh
Get system installed build dependencies also during pip download to avoid installing them from source.
> METAL-1164: Add pip no-build-isolation to download command

- main-packages-list.ocp
Bumping python-waitress to 3.0.1
> OCPBUGS-43959, OCPBUGS-43951: Bump python-waitress

- main-packages-list.ocp
This includes the fix for CVE available in 3.1.5
> [4.16] OCPBUGS-48151,OCPBUGS-48598: Bump jinja2 to 3.0.1-6.el9.2

- main-packages-list.ocp
This includes the fix for CVE available in 3.1.5
> [4.15] OCPBUGS-48148,OCPBUGS-48597: Bump jinja2 to 3.0.1-6.el9.2

- main-packages-list.ocp
This includes the fix for CVE available in 3.1.5
> [4.14] OCPBUGS-48147,OCPBUGS-48594: Bump jinja2 to 3.0.1-6.el9.2

- main-packages-list.ocp
This includes the fix for both CVEs available in 3.1.5
> [4.13] OCPBUGS-48146,OCPBUGS-48595: Bump jinja2 to 3.0.1-6.el9.2

- main-packages-list.ocp
This includes the fix for both CVEs available in 3.1.5
> [4.12] OCPBUGS-48145,OCPBUGS-48596: Bump jinja to 3.0.1-6.el9.2

- scripts/runhttpd
- scripts/runironic
- scripts/runlogwatch.sh
The inotify-tools last release is from september 2023 and last update in the repo is 7 months old (May 2024). The inotify-tools package is not present in the EPEL10 repo anymore while python3-inotify is in a native repository. This change allows us to remove dependency from EPEL entirely.
(cherry picked from commit 9f700307f469632da9d7f7940eeeb479235fd0b6)
> OCPBUGS-49755: Use pynotify instead of inotify-tools

- scripts/runhttpd
- scripts/runironic
- scripts/runlogwatch.sh
The inotify-tools last release is from september 2023 and last update in the repo is 7 months old (May 2024). The inotify-tools package is not present in the EPEL10 repo anymore while python3-inotify is in a native repository. This change allows us to remove dependency from EPEL entirely.
(cherry picked from commit 9f700307f469632da9d7f7940eeeb479235fd0b6)
> OCPBUGS-49756: Use pynotify instead of inotify-tools

- scripts/runlogwatch.sh
(cherry picked from commit dc60eca6b6189d619d909fbecfb75a124655c81d)
> OCPBUGS-49829: Fix runlogwatch failure if LOG_DIR does not exist

- main-packages-list.ocp
- main-packages-list.okd
The python3-inotify package is installed as dependency but it should be explicitly mentioned in the packages list to avoid issues like https://github.com/okd-project/okd/issues/2113
> OCPBUGS-50613: Install python3-inotify pkg explicitly

- scripts/runlogwatch.sh
Use correct values for read command, and remove colors from output.
a pyinotify event looks like this:
<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 > by default the output contains colorize text that is interpreted literally by variable conversion in the tar command, so not only we have to parse it, but
we also need to get just raw format output.
(cherry picked from commit 9e2d94ae3e6fd487ed0b59d24e68e0c1c81f16ce)
> OCPBUGS-51310: Fix runlogwatch script

- scripts/runlogwatch.sh
Use correct values for read command, and remove colors from output.
a pyinotify event looks like this:
<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 > by default the output contains colorize text that is interpreted literally by variable conversion in the tar command, so not only we have to parse it, but
we also need to get just raw format output.
(cherry picked from commit 9e2d94ae3e6fd487ed0b59d24e68e0c1c81f16ce) (cherry picked from commit 09c68d21332c166d4929a922387509fb199fc701)
> OCPBUGS-52290: Fix runlogwatch script

- scripts/runlogwatch.sh
Use correct values for read command, and remove colors from output.
a pyinotify event looks like this:
<Event dir=False mask=0x8 maskname=IN_CLOSE_WRITE name=mylogs.gzip path=/shared/log/ironic/deploy pathname=/shared/log/ironic/deploy/mylogs.gzip wd=1 > by default the output contains colorize text that is interpreted literally by variable conversion in the tar command, so not only we have to parse it, but
we also need to get just raw format output.
(cherry picked from commit 9e2d94ae3e6fd487ed0b59d24e68e0c1c81f16ce) (cherry picked from commit 09c68d21332c166d4929a922387509fb199fc701)
> OCPBUGS-52292: Fix runlogwatch script

- Dockerfile.ocp
They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
> METAL-1299: Do not use openstack packages

- Dockerfile.ocp
They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
(cherry picked from commit 434c33e21fa1ac887471c90d60de8af14a0a42b5)
> METAL-1302: Do not use openstack packages

- Dockerfile.ocp
They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
(cherry picked from commit 434c33e21fa1ac887471c90d60de8af14a0a42b5)
> METAL-1305: Do not use openstack packages

- Dockerfile.ocp
They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
(cherry picked from commit 434c33e21fa1ac887471c90d60de8af14a0a42b5)
> METAL-1306: Do not use openstack packages

- scripts/runlogwatch.sh
Currently, there is what seems to be a buffering problem: the file names
sometimes do not come before the content but rather at the end of a
random line. In an attempt to fix it, I'm switching from extracting all
files to listing files and extracting them one by one.
I'm also adding extra new lines to make the output more readable.
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>
> OCPBUGS-55381: Extract files one-by-one in logwatch

- requirements.cachito
> METAL-1344: Do not install sushy-oem-idrac separately

- ironic-config/ironic.conf.j2
The local RPC is enabled in 4.20 even if JSON RPC itself is disabled, so
the port must be set outside of the condition.
Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>
> OCPBUGS-60455: set [json_rpc]port unconditionally

- requirements.cachito
This commit aims to update the hash of ironic and sushy, the latest commit have the fixes for idrac10
> [4.20] OCPBUGS-52427: Bump ironic and sushy to fix idrac10
