Dockerfile.ocp
Applying upstream changes to Dockerfile.ocp for Ironic Stein
=> Update Dockerfile.ocp for Ironic Stein

Dockerfile.ocp
Make a trivial formatting change to trigger an image build.
=> Trigger an image build.

Dockerfile.ocp, prepare-ipxe.sh
=> Bug 1737086: Sync master fixes to release-4.2

configure-ironic.sh
Bringing https://github.com/metal3-io/ironic-image/pull/105 into openshift fork
=> Enable fast_track provisioning for nodes

Dockerfile.ocp, configure-ironic.sh, inspector.ipxe, ironic.conf, runironic-exporter.sh
applying latest changes to 4.3 branch as they were not automatically merged
=> Bug 1778237: apply latest changes to 4.3

Dockerfile.ocp, ironic.conf
=> Add redfish UEFI virtual media boot

Dockerfile.ocp, ironic.conf
Manual importing metal3-io#116
The import to master that will be automatically ported to 4.4 and 4.5 is here #35
=> Bug 1781217: Add redfish UEFI virtual media boot

Dockerfile.ocp
We need to increase the size of the esp image for downstream
compatibility.
=> Increase esp image size

Dockerfile.ocp
=> Bug 1784500: Esp build x86 64 only

Dockerfile.ocp
=> Bug 1784086: Increase esp size

Dockerfile.ocp, rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runironic.sh, runmariadb.sh
Cherry-pick from metal3-io ironic-images
https://github.com/metal3-io/ironic-image/commit/f380833579ae0d36b7ca87287ad2ee1b8dbb7011
https://github.com/metal3-io/ironic-image/commit/8b4ceb63cc811b5885c1b2cd7b89360ede44203a
=> Stop log files + Remove iptables filters

Dockerfile.ocp, rundnsmasq.sh, runhttpd.sh, runironic-api.sh, runironic-conductor.sh, runironic.sh, runmariadb.sh
Cherry-pick from metal3-io ironic-images
metal3-io@f380833
metal3-io@8b4ceb6
=> Bug 1810485: Stop log files + Remove iptables filters

Dockerfile.ocp, ironic.conf
=> Virtmedia fixes2

Dockerfile.ocp, OWNERS, README.md, configure-ironic.sh, ironic.conf.j2, prepare-image.sh, rundnsmasq.sh, runmariadb.sh
This is a real merge to ensure we have easier time from now on.
=> Merge metal3-io/ironic-inspector-image as of Nov 30, 2020

Dockerfile.ocp, Dockerfile.okd, config/ironic.conf.j2
Reviews and help with testing is welcomed.
/cc @vrutkovs 
if we want to onboard this to Prow, we'll need to ensure Fedora 33 and CentOS 8 images are available there.
=> Add Support for Fedora-based OKD

main-packages-list.txt
Resolves: rhbz#1961717
Signed-off-by: Lon Hohberger <lhh@redhat.com>
=> Bug 1961717: Update remaining out of date deps to Wallaby versions

main-packages-list.txt
(cherry picked from commit efbc012b170a80070d157033dd1fe3284d9be5d1)
=> Bug 1972213: Update python-ironic-lib

main-packages-list.txt
Sync latest code for bugfixes and improvements
=> Update packages version

scripts/configure-ironic.sh
metal3-io related change https://github.com/metal3-io/ironic-image/pull/291
=> Bug 1990316: Fix missing port in iso http url

ironic-config/apache2-ironic-api.conf.j2
(cherry picked from commit 4eb559a9d2306e130882598aeb60f95f3ea27ccd)
=> Bug 2001519: Don't allow unauthenticated access to Ironic

Dockerfile.ocp, Dockerfile.okd
Please check that this makes sense for aarch64.
/cc ﻿@jeremyfreudberg
/cc @elfosardo
=> Create EFI esp.img on aarch64

main-packages-list.txt, scripts/ironic-common.sh
This is a backport of https://github.com/openshift/ironic-image/pull/220 to 4.9.
=> Bug 2023748: Compare IPs using the short form of IPv6 address

main-packages-list.txt, scripts/ironic-common.sh
This is a backport of https://github.com/openshift/ironic-image/pull/220 to 4.8
=> Bug 2023765: Compare IPs using the short form of IPv6 address

scripts/coreos-ipa-common.sh
Cherry-picked from https://github.com/metal3-io/ironic-image/pull/337
=> Use IPv6-friendly URLs for CoreOS

Dockerfile.okd, ironic-config/apache2-ironic-api.conf.j2, ironic-config/apache2-vmedia.conf.j2, ironic-config/dnsmasq.conf.j2, ironic-config/inspector.ipxe.j2, ironic-config/ironic.conf.j2, ironic-inspector-config/inspector-apache.conf.j2, prepare-efi.sh, scripts/configure-httpd-ipa.sh, scripts/configure-ironic.sh, scripts/ironic-common.sh, scripts/runhttpd, scripts/runironic-inspector, scripts/tls-common.sh
also avoid unbound variables and other surprises in ironic-common
See https://github.com/metal3-io/ironic-image/pull/370
Also adding https://github.com/openshift/ironic-image/pull/263/commits/9d21eef7c7838ac97620aec64d0e125b923be589
to fix OKD image thanks to @jeffdyoung
=> Sync with ironic-image metal3 2022-04-12

Dockerfile.ocp
=> Fix patch path

ironic-config/dnsmasq.conf.j2, main-packages-list.ocp, main-packages-list.okd, prepare-ipxe.sh, scripts/rundnsmasq
Waiting for ipxe artifacts to become available.
https://issues.redhat.com/browse/ARMOCP-236
=> Add ipxe support for arm64

OWNERS
Updating to most recent team composition
=> [OCP 4.8] Update OWNERS

ironic-inspector-config/inspector-apache.conf.j2, scripts/ironic-common.sh, scripts/runhttpd
Include fix for https://bugzilla.redhat.com/show_bug.cgi?id=2081734
=> Sync with upstream metal3-io ironic-image

main-packages-list.ocp
See https://review.opendev.org/c/openstack/ironic/+/854760
=> Bug 2104275: sync the ValueDisplayName fix

main-packages-list.ocp
- https://opendev.org/openstack/ironic/commit/c6936cc6389aa8396480aecf8d71cdf50eb42fae
- https://opendev.org/openstack/ironic/commit/d85d7f8ac52f289b7b01096c65757b68791f4bd4
- https://opendev.org/openstack/sushy/commit/96fc2057dcfb544ed12afe6e5ed2e289e7fbaf76
As well as the ETag workaround:
- https://opendev.org/openstack/sushy/commit/56182b39cf5748aea599281677dd3ddb07b6d905
=> OCPBUGS-1225: sync BIOS settings fixes

README.md, ironic-config/dnsmasq.conf.j2, scripts/rundnsmasq
(cherry picked from commit dd743a91ef1b502a0eb3c3858629a3990b07514b)
=> Add DNS or GW for use by dnsmasq

main-packages-list.ocp
This is to include latest bug fixes and updates
=> OCPBUGS-4635: Update packages versions with latest available

main-packages-list.ocp
This is to include latest bug fixes and updates
=> OCPBUGS-4789: Update packages versions with latest available

main-packages-list.ocp
This is to include latest bug fixes and updates
=> OCPBUGS-4908: Update packages versions with latest available

main-packages-list.ocp
This is to include latest bug fixes and updates
=> OCPBUGS-5415: Update packages versions with latest available

scripts/configure-ironic.sh, scripts/runironic-inspector
Ensure internal ironic traffic bypasses any proxies
=> OCPBUGS-5461: Add ironic IP to no_proxy

main-packages-list.ocp
Patched version includes fix for
https://bugzilla.redhat.com/show_bug.cgi?id=2196643
=> OCPBUGS-13587: Add python-flask dependency

main-packages-list.ocp
Patched version includes fix for
https://bugzilla.redhat.com/show_bug.cgi?id=2196643
=> OCPBUGS-13586: Add python-flask dependency

main-packages-list.ocp
This include the very imporant fix:
- DB: Fix result set locking with periodics https://review.opendev.org/c/openstack/ironic/+/888188
=> Ironic package upgrade

main-packages-list.ocp
This includes the attach/detach iso change
=> NO-ISSUE: Update ironic packages version

main-packages-list.ocp
Also adds some RAID-related fixes. Sync PR:
https://github.com/openshift/openstack-ironic/pull/79
=> OCPBUGS-9303: include the secure boot retry

main-packages-list.ocp, requirements.cachito
This adds the redfish implementation of attach/detach generic iso.
=> METAL-804: Bump ironic hash to include recent fixes and features

main-packages-list.ocp, requirements.cachito
Cachito does not recognize tags, using the package instead.
=> NO-ISSUE: Use microversion-parse package

scripts/auth-common.sh
Merging the contents of https://github.com/metal3-io/ironic-image/pull/506/files downstream (with needed additions for ironic-inspector)
=> OCPBUGS-29687: Read ironic and inspector htpasswds from files

requirements.cachito
https://review.opendev.org/c/openstack/sushy/+/925853
=> OCPBUGS-38077: update sushy to pick up the RAID fix

Dockerfile.fcos, Dockerfile.scos
https://github.com/openshift/ironic-image/pull/532  removes ironic inspector but missed scos and fcos dockerfiles
=> NO-ISSUE: fix scos and fcos dockerfiles to remove ironic-inspector

requirements.cachito
This is a duplicate for @iurygregory 's pr - https://github.com/openshift/ironic-image/pull/562
=> [4.17] OCPBUGS-38784: Update sushy to include Huwaei Fix ( Duplicate PR )

prepare-image.sh
The wheel package should not stay in the final image
=> METAL-1155: Remove wheel after build is done

requirements.cachito
Set node "alive" when inspection finished
=> OCPBUGS-44895: Bump Ironic

requirements.cachito, tools/check-requirements.sh
The ironic source code does not depende from ironic-lib anymore.
=> METAL-1251: Remove dependency from ironic-lib

main-packages-list.ocp, requirements.cachito
Reverts openshift/ironic-image#667
=> METAL-1496: Revert "OCPBUGS-55298: Bump ironic to latest"

README.md, ironic-config/ironic.conf.j2, scripts/runironic-exporter
(cherry picked from commit b810041acd87d69a35de2e368f0964cbfb0577ab)
=> METAL-1461: update config to allow Ironic to work with ironic-prometheus-exporter

main-packages-list.ocp, requirements.cachito
=> METAL-1574: Remove temporary dependencies from source

requirements.cachito
Updating ironic and sushy to the latest commits, so we can have the fixes for each story mentioned in the title.
=> METAL-1566,METAL-1577,METAL-1446: Sync Ironic and Sushy
